"""added user_id

Revision ID: 4c8dd2e1494c
Revises: a07aeebfaa2f
Create Date: 2022-09-14 11:33:50.073825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8dd2e1494c'
down_revision = 'a07aeebfaa2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
