"""field added

Revision ID: 55d5dd3dccea
Revises: e0ea7b423ea5
Create Date: 2022-09-13 11:03:52.051476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d5dd3dccea'
down_revision = 'e0ea7b423ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_stu_adm-pricing_plan-book', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_stu_adm-pricing_plan-book', 'tbl_stu_usr-users', ['user_id'], ['id'])
    op.add_column('tbl_stu_adm-pricing_plan-book_type', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_stu_adm-pricing_plan-book_type', 'tbl_stu_usr-users', ['user_id'], ['id'])
    op.add_column('tbl_stu_adm-pricing_plan-book_type_has_book', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_stu_adm-pricing_plan-book_type_has_book', 'tbl_stu_usr-users', ['user_id'], ['id'])
    op.add_column('tbl_stu_adm-pricing_plan-service_has_subject', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_stu_adm-pricing_plan-service_has_subject', 'tbl_stu_usr-users', ['user_id'], ['id'])
    op.add_column('tbl_stu_adm-pricing_plan-subject', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_stu_adm-pricing_plan-subject', 'tbl_stu_usr-users', ['user_id'], ['id'])
    op.add_column('tbl_stu_adm-pricing_plan-subject_has_book', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_stu_adm-pricing_plan-subject_has_book', 'tbl_stu_usr-users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_stu_adm-pricing_plan-subject_has_book', type_='foreignkey')
    op.drop_column('tbl_stu_adm-pricing_plan-subject_has_book', 'user_id')
    op.drop_constraint(None, 'tbl_stu_adm-pricing_plan-subject', type_='foreignkey')
    op.drop_column('tbl_stu_adm-pricing_plan-subject', 'user_id')
    op.drop_constraint(None, 'tbl_stu_adm-pricing_plan-service_has_subject', type_='foreignkey')
    op.drop_column('tbl_stu_adm-pricing_plan-service_has_subject', 'user_id')
    op.drop_constraint(None, 'tbl_stu_adm-pricing_plan-book_type_has_book', type_='foreignkey')
    op.drop_column('tbl_stu_adm-pricing_plan-book_type_has_book', 'user_id')
    op.drop_constraint(None, 'tbl_stu_adm-pricing_plan-book_type', type_='foreignkey')
    op.drop_column('tbl_stu_adm-pricing_plan-book_type', 'user_id')
    op.drop_constraint(None, 'tbl_stu_adm-pricing_plan-book', type_='foreignkey')
    op.drop_column('tbl_stu_adm-pricing_plan-book', 'user_id')
    # ### end Alembic commands ###
