"""field added more

Revision ID: 6273bacebc11
Revises: 69724e09683d
Create Date: 2022-09-20 13:56:02.061672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6273bacebc11'
down_revision = '69724e09683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_order_and_payment-plan_order', sa.Column('status_date', sa.DateTime(), nullable=True))
    op.add_column('tbl_order_and_payment-plan_order', sa.Column('service_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_order_and_payment-plan_order', 'tbl_order_and_payment-order', ['service_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_order_and_payment-plan_order', type_='foreignkey')
    op.drop_column('tbl_order_and_payment-plan_order', 'service_order_id')
    op.drop_column('tbl_order_and_payment-plan_order', 'status_date')
    # ### end Alembic commands ###
