"""plan user_id added

Revision ID: 84073176aa9b
Revises: 6273bacebc11
Create Date: 2022-09-21 10:23:55.715737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84073176aa9b'
down_revision = '6273bacebc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
